# Darwin's Lizards

author: "Jonathan B. Losos and Kevin de Queiroz"

Natural History. Dec97/Jan98, Vol. 106 Issue 11, p34. 6p. 10 Color Photographs.

Like Galapagos finches, anoles of the Greater Antilles have proved to be eminently adaptable. The term "tropical biodiversity" is more likely to conjure up images of Amazonian rain forests than Jamaican beach resorts. Yet to study the causes of species richness, we travel to Negril, home to such vacation get-aways as Sandals and Hedonism II. Like most denizens of Negril, our subjects are sun lovers; their preferred basking spots, however, are not beach towels but tree trunks. Beautiful, scaly, and found just about anywhere in Negril but on the beach itself, Jamaican anoles (lizards of the genus Anolis) are a living test case for our investigations into the workings of evolution. 

Even a leisurely stroll around Negril reveals an abundance and diversity of lizards. At the bases of trees and wooden posts, two species perch head downward. One, the Jamaican lined anole, prefers shadier spots, whereas the brown anole basks on fence posts out in the open. Four other species are found farther up in the trees. The two most common run and jump from branch to branch, using trunks and leaves as necessary. They have slightly different temperature preferences but mainly differ in size and color, the beautiful blue Graham's anole being twice the weight of the smaller and paler opalescent anole. The king of the treetops, and the giant among Negril's tree-dwelling anoles, is the fifteen-inch-long "green guana," as the locals call it. This fearless, lime-colored lizard supplements its diet of insects with small vertebrates, including other anoles. The anole that is possibly the most numerous is also the most rarely seen. A cautious demeanor and camouflage markings make the Valencienne's anole difficult to spot as it creeps along narrow branches and twigs in search of hidden prey. This short-legged lizard is not a sprinter or leaper; it eludes predators by avoiding detection in the first place. 

Each of these six species is adapted to its own ecological niche, in particular to the surface on which it lives and moves. The stubby legs of Valencienne's anole, for example, may not give the animal speed but are well suited for maintaining balance on narrow twigs. In contrast, anoles that spend their lives closer to the ground have extremely long hind limbs that provide great sprinting and jumping capabilities (as we determined in the field, using a portable lizard racetrack and long-jump pit). These lizards sit motionless for long periods, their athletic prowess held in check as they scan the ground surrounding their perch. When an unwary insect wanders within range, the lizards dart out to capture a meal. 

Anoles have also adapted to life in the trees by evolving adhesive toe pads, like those of their cousins the geckos. These pads, which are covered by millions of microscopic, hairlike structures, allow lizards to cling to the smooth and irregular surfaces of leaves and narrow branches. Species that dwell high in the trees have a greater need to maintain their grip; they generally have more well-developed toe pads than do species that live closer to the ground. 

This array of anoles constitutes a classic case of adaptive radiation, a common phenomenon on islands in which the first species to arrive, finding a realm of untapped ecological niches, gives rise to a diversity of descendant species, each adapted to use a different part of the environment. The most famous case of adaptive radiation is that of Darwin's finches, in the Galapagos Islands, but there are many others, including Hawaiian honeycreepers and East African Rift Lake cichlids.

The adaptive radiation of Caribbean anoles, however, is exceptional in two regards. First, Caribbean anoles have experienced not one but four adaptive radiations, by diversifying independently on each island of the Greater Antilles--Cuba, Jamaica, Puerto Rico, and Hispaniola (which encompasses the countries of Haiti and the Dominican Republic). Second, and more surprisingly, these independent radiations have produced remarkably similar sets of species on each island (see table at left). For example, the slender, twig-hugging Valencienne's anole lives on Jamaica, but each of the other islands hosts a species extremely similar in build and coloration that uses the same habitats and behaves in much the same way. Each of the four islands also has at least one long-legged species that perches motionless near the ground using a sit-and-wait foraging strategy to ambush prey; a shorter-limbed arboreal species with large toe pads, which moves throughout the trees and has the ability to change colors dramatically (from green or blue to brown); and a large species that lives high in the crown of trees. Although such convergent evolution is a widespread phenomenon in both the animal and plant kingdoms, convergence of entire sets of adaptive radiations has rarely been documented--and never before in quadruplicate. 

The outcomes of the independent radiations, however, has not been identical. Cuba and Hispaniola, but not Jamaica and Puerto Rico, host a tree-trunk specialist with a flattened body, while Cuba alone has a large anole that lives near streams, catches fish, and runs across water to escape predators, much like the Central American basilisk lizard. Similarly, in Hispaniola, a small anole inhabits the leaf litter of mountainous rain forests; the unusual structure of its vertebrae may be an adaptation for hopping. All four Greater Antillean islands have stream and rain forest habitats, so the existence of only a single stream specialist and a single leaf-litter specialist is a mystery. Further investigation may eventually reveal why certain ecological niches are adapted to repeatedly while others are not. 

Given their diversity, one might predict that these island anoles have been in the Caribbean for quite some time, and indeed they have. Few anole fossils exist, but a dozen amber-entombed specimens, all but one from deposits in the Dominican Republic, are from fifteen to twenty million years old. When we compared two of these specimens with living Dominican species, we found that the fossil lizards were virtually identical to the shorter-limbed, color-changing tree lizards on the island today. Our studies could not reveal whether the fossil anoles and extant Dominican lizards are close relatives or distant relatives that have converged to look alike. But they do indicate that the evolutionary con vergence observed today in lizards throughout the Greater Antilles is an ancient phenomenon. 

Even without fossils, much can be inferred from comparisons of living species. For example, all Jamaican anoles, with the exception of the brown anole (a natural colonist that arrived from Cuba relatively recently, perhaps a few thousand years ago), have a unique combination of skeletal features, suggesting that they descended from a single ancestral species that originally colonized the island. studies support this conclusion, showing that anole evolution proceeded essentially independently on each island. Furthermore, with one possible exception, the anoles that became specialized to use a particular habitat on one island are not closely related to their ecological counterparts on the other islands. 

Despite decades of work by many researchers in the Caribbean, new species of anoles are still encountered every year. The mountains of eastern Cuba, a particularly rich source of new discoveries, are being investigated by teams of biologists from the United States and Cuba. At the same time, however, the destruction of natural habitats is threatening the survival of some species. The large Roosevelt's anole, from the islands east of Puerto Rico, is already feared extinct, and several other forest-dwelling species from Central America are known to have inhabited areas that are now completely deforested. One can only guess how many species have perished along with the forests of Haiti, which now occupy only 2 percent of their original area. While some of the more common anoles thrive in human-altered habitats, others are sensitive. Only by conserving island forests can these natural laboratories of evolution be preserved for the enjoyment and the enlightenment of future generations. 

### [**Welcome to the Sunshine State**](#toc "Welcome to the Sunshine State")

Florida is one of the most biologically rich areas in North America, but not all of its fauna is native. Today, the most abundant anole in Florida is an emigre from Cuba. Common and widely distributed in the Caribbean, the six-inch-long brown anole can be found perched on almost any tree trunk, brush pile, or fence post in its range. In the 1960s, the brown anole was generally restricted to Florida seaports, but it has since flourished and spread northward. Its ascendancy, how ever, has come at a cost to the native green anole. (This lizard, sometimes misleadingly called the American chameleon, is often sold in pet stores.) Although little data about the interactions of the native and introduced species have been published, any Florida old-timer will tell you the same thing: before the brown anole arrived, green anoles were a lot more common. In all, seven anole species have been introduced into Florida. They include representatives of all four Greater Antillean radiations and the largest of all 400 living anole species, the eighteen-inch-long Cuban knight anole. 

### [**Niche Neighbors**](#toc "Niche Neighbors")

Anoles that share extremely close ecological quarters--part of the same tree trunk, for example--need to minimize competition for food and perches. Fine-tuned physiological adaptations help solve this problem. In Puerto Rico, both the crested anole and Gundlach's anole perch low on tree trunks and for age on the ground. They can coexist because the crested anole prefers sunny areas where it can bask and raise its body temperature to 86 Fahrenheit, while Gundlach's anole is more often found in deep forest shade and is comfortable at a body temperature closer to 78 Fahrenheit. In transition zones, where the forest gives way to open areas, the two species can share a tree trunk; one will be active when the trunk is in the sun, the other when it is cloaked in shade. Such coexistence is carried to the extreme in western Cuba, where four species divide the base-of-the-tree habitat by using areas differing slightly in temperature, humidity, and illumination. 

Another requisite for an anole with close neighbors is the ability to recognize members of its own species, and thus avoid wasting time in misdirected courtship or territorial displays. (In most species, males defend their territories only against other males of the same species.) Sharp eyesight and color vision are the keys to knowing who's who. A male, whether it is wooing a female or defending its turf, displays by raising its head and forequarters, bobbing its head up and down, and extending a collapsible expanse of skin, called a dewlap, from its throat. Each anole species has its own stereotyped pattern and frequency of head-bob movements. Video playback experiments show that anoles recognize their own species' display cadence. The brightly colored and often strikingly distinct dewlaps also serve as species ID cards. For example, the dewlaps of the Cuban base-of-the-tree anoles are unmistakable: one is white, another is orange with yellow spots, a third is red with a white rim, and the fourth is yellow with big splashes of red. Laboratory experiments show that male anoles will ignore males of their own species that have had their dewlaps painted a different color (with removable lipstick) but will react aggressively toward males of other species whose dewlaps have been colored to resemble their own. 

In the Greater Antilles, Anolis lizards that adapted to corresponding niches look alike, although they are not closely related. Below is a sampler of niche holders listed by species name and a photo of one member of each category. 

```         
Tree crown
Large body, large toe pads

Cuba--Anolis equistris
Hispaniola--A. ricordii
Jamaica--A. garmani
Puerto Rico--A. cuveiri

Upper trunk/canopy
Large toe pads, can change color

Cuba--Anolis porcatus
Hispaniola--A. chlorocyanus
Jamaica--A. grahami
Puerto Rico--A. evermanni

Twig
Short body, slender legs and tail

Cuba--Anolis angusticeps
Hispaniola--A. insolitus
Jamaica--A. valencienni
Puerto Rico--A. occultus

Midtrunk
Long forelimbs, vertically
flattened body

Cuba--Anolis loysiana
Hispaniola--A. distichus
Jamaica--none found
Puerto Rico--none found

Lower trunk/ground
Stocky body, long hind limbs

Cuba--Anolis sagrei
Hispaniola--A. cybotes
Jamaica--A. lineatopus
Puerto Rico--A. gundlachi

Grass/bush
Slender body, very long tail

Cuba--Anolis alutaceus
Hispaniola--A. olsonni
Jamaica--none found
Puerto Rico--A. pulchellus
```
